# Use the official Python image from the Docker Hub
FROM python:3.9-slim


# Create and set the working directory
WORKDIR /app 

# Copy the requirements file
COPY requirements.txt .
# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY RAG.py /app/
COPY FixAgent.py /app/
COPY config.ini /app/

# Expose the port FastAPI will run on
EXPOSE 8085

# Run the FastAPI application using uvicorn
CMD ["uvicorn", "FixAgent:app", "--host", "0.0.0.0", "--port", "8085"]
