# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# If you have a requirements.txt file, uncomment the next line
RUN pip install -r requirements.txt

COPY . .

# Expose the port that FastAPI will run on
EXPOSE 8082

# Define the command to run the application using uvicorn
CMD ["uvicorn", "IntegrationAgent:app", "--host", "0.0.0.0", "--port", "8082"]