services:
  buyagent:
    build:
      context: ./BuyerAgent
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  
    depends_on:
      - integrationagent

  integrationagent:
    build:
      context: ./IntegrationAgent
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - vendoragent
      - securityagent
      - fixagent
  vendoragent:
    build:
      context: ./VendorAgent
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  securityagent:
    build:
      context: ./SecurityAgent
      dockerfile: Dockerfile
    ports:
      - "8084:8084" 
      
  fixagent:
    build:
      context: ./FixAgent
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
  # knowledgebase:
  #   build:
  #     context: ./KnowledgeBase
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./KnowledgeBase/KnowledgeData.json:/app/KnowledgeData.json
  #   depends_on:
  #     - db
  db:
    build:
      context: ./pgvector-postgres
      dockerfile: Dockerfile
    container_name: pgvector-containersbom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aisbom
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./KnowledgeBase/Knowledgebase.sql:/docker-entrypoint-initdb.d/Knowledgebase.sql:ro
    entrypoint: ["docker-entrypoint.sh", "postgres"]
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ajukhaja786@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  postgres_data:
